# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  merge:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: git pull origin master
      - run:
          command: git push origin demo
    branches:
      only:
        - demo
workflows:
  version: 2
  build_and_merge:
    jobs:
      - merge