# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  deploy:
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          HEROKU_APP_NAME: test-ci-on-heroku
          HEROKU_API_KEY: 242f0ab1-f311-4ce3-a76f-3d82f5794edf
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Deploy master to Heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  build_and_merge:
    triggers:
      - schedule:
          cron: "0,10,20,30,40,50 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - deploy
  normal_deploy
    jobs:
      - deploy
          